### ISSUE TITLE
Device::Osram::Lightify::API driver for Power::Outlet

### ISSUE THREAD

**Issue by mrdvt92** [skx/Device-Osram-Lightify#1]
Steve,
Can you please write an Osram driver for the Power::Outlet API?

I would put it in the Power::Outlet::Osram name space so you should be able to control it with a command like.

power-outlet Osram ON mac 12:34:56:78

or configure the CGI app with an INI entry like

[light1]
type=Osram
host=hub
mac=12:34:56:78

Thanks,
Mike

https://metacpan.org/release/Power-Outlet
mrdvt92

**Comment by skx** [comment]
Osram make two things that are controlled via the same hub:
- Light bulbs.
- Switches.

I don't own any of the switches so I sadly cannot write a module beneath the `Power::Outlet` name-space to control those types of devices, even though  I expect they work the same as the bulbs,  I don't know for sure and couldn't test them.

(I don't think you were suggesting copying/pasting all the current code I've written just to create a `Power::Outlet::Osram::Light` module, instead you were thinking of the switch-devices.)

Before writing my module I searched CPAN for "hue", "philips", "light" and similar, and didn't find anywhere I could sensible drop in my desired code. I didn't find `Power::Outlet` for example.  But right now I'd suggest if you _did_ mean you'd like to manage these lights via that module it would be easiest to write a small shim than copy and paste the code.

I'd probably be willing to contribute such a compatibility layer if the dependency on this module/code would  be accepted.

**Comment by mrdvt92** [comment]
Steve,Sorry just saw this.   > you'd like to manage these lights via that module it would be easiest to write a small shim Yep just a simple package in your distribution called Power::Outlet::Osram.  It would be good if it would support both lights and switches in the same name space if they speak the same protocol. It looks like your Light package is dependent on your Hub package so you will need to initialize the light inside outwards from the way you are currently constructing.Thanks,Mike 
 

```
  From: Steve Kemp <notifications@github.com>
```

 To: skx/Device-Osram-Lightify Device-Osram-Lightify@noreply.github.com 
Cc: Michael R. Davis mrdvt92@yahoo.com
 Sent: Saturday, January 2, 2016 1:57 AM
 Subject: Re: [Device-Osram-Lightify] Device::Osram::Lightify::API driver for Power::Outlet (#1)

Osram make two things that are controlled via the same hub:   
- Light bulbs.
- Switches.
  I don't own any of the switches so I sadly cannot write a module beneath the Power::Outlet name-space to control those types of devices, even though I expect they work the same as the bulbs, I don't know for sure and couldn't test them.(I don't think you were suggesting copying/pasting all the current code I've written just to create a Power::Outlet::Osram::Light module, instead you were thinking of the switch-devices.)Before writing my module I searched CPAN for "hue", "philips", "light" and similar, and didn't find anywhere I could sensible drop in my desired code. I didn't find Power::Outlet for example. But right now I'd suggest if you did mean you'd like to manage these lights via that module it would be easiest to write a small shim than copy and paste the code.I'd probably be willing to contribute such a compatibility layer if the dependency on this module/code would be accepted.—

**Comment by skx** [comment]
You didn't answer my question about whether you'd accept the dependency.

If you did then you're free to take the code I've placed here:

https://gist.github.com/skx/ea50198c7891522ffe45
