### ISSUE TITLE
Light names

### ISSUE THREAD

**Issue by Tekki** [skx/Device-Osram-Lightify#4]
Names of lights are UTF-8 strings. Maybe we should decode them to Perl characters.
What do you think of that? Shall I prepare a pull request?

**Comment by skx** [comment]
That would be great, and I'd be happy to accept such a pull-request.

**Comment by Tekki** [comment]
I've created a pull request. Behavior of bin/ol should be the same as before, but now we are able to write in a program something like
```
use utf8;
...
if ($light->name eq 'Küche') { ... }
```
For those who already decode $light->name, this is a breaking change.

**Comment by skx** [comment]
Closed in #5.  Thanks for your report, & solution.

I'll run perltidy over the module, and issue a push a new release to CPAN shortly

**Comment by Tekki** [comment]
Didn't realize you use perltidy, I just tried to imitate your style. In any case I work with much more compact settings (less line breaks, less spaces) than you.

**Comment by skx** [comment]
Not a big deal, but I [use this .perltidyrc globally](https://github.com/skx/dotfiles/blob/master/.perltidyrc).   It might not be perfect, but I figure consistency is more important than perfection.
