### ISSUE TITLE
Issue new release

### ISSUE THREAD

**Issue by skx** [skx/Device-Osram-Lightify#8]
* [x] Tidy
* [x] Update Changlog
* [x] Tag
* [x] Upload to CPAN

**Comment by Tekki** [comment]
Maybe for the new version we should implement `ol --help`.

**Comment by skx** [comment]
Added `--help` support now.  Also ensure `--host` is specified.

**Comment by Tekki** [comment]
There is a confusion with --host and --hub parameters (to call it 'host' is probably the better idea).
By the way, Getopt::Long exports GetOptions by default, so you can just write `GetOptions(...);`

**Comment by skx** [comment]
Yeah I noticed the same thing - so I pushed out 0.7.1 immediately afterwards.  That's what happens when I do things in a rush because I'm busy :(
